### ISSUE TITLE
Update to latest craftbukkit

### ISSUE THREAD

**Issue by confuser** [kumpelblase2/Remote-Entities#10]
http://pastebin.com/3U5gb7ag

**Comment by kumpelblase2** [comment]
As of the latest commits from craftbukkit, I'll need to use new imports every update because of nms calls. I'll see if I can do that dynamically, so I just need to recompile instead of changing it by hand all the time.

**Comment by confuser** [comment]
Is this of any help?

http://forums.bukkit.org/threads/support-multiple-minecraft-versions-with-abstraction-maven.115810

**Comment by Lolmewn** [comment]
^ Yes. Waiting for this too :D

**Comment by kumpelblase2** [comment]
Well, I'm figuring out a system to use this bad bukkit decision (the given alternatives were by far better in my opinion) as an advantage. Or not. Maybe just being able to build this at any time for any minecraft version - without needing to checkout an earlier version.
I already have an idea on how most of it would be possible, but well, not everything.
I'll just write a script that converts the version for the time being, but there'll be a better way soon.

**Comment by kumpelblase2** [comment]
See 4b884bacf2 for the update for the 1.4.5-R1.0. However, I'm not done yet. More things for this topic will be up on the weekend!

**Comment by confuser** [comment]
Awesome, what version is this in Maven? I presume it would be 1.3, but It seems 1.3-SNAPSHOT doesn't exist?

**Comment by kumpelblase2** [comment]
I haven't had it pushed to the repo at that point. Now it is and the version is 1.3 including javadocs.

**Comment by confuser** [comment]
Sorry to re-open, but noticed what I think is a mistake which may be in other classes, you have

import net.minecraft.server.v1_4_5.EntityLiving;

Shouldn't that be import net.minecraft.server.EntityLiving; ?

http://pastebin.com/z0UgitAf

**Comment by kumpelblase2** [comment]
Not anymore. They made a bad decision (imo, at least how they executed the idea) so that every minecraft update the package names get changed. And since a RB including this change just came out, this should be correct. However, there's no version for 1.4.6 yet because not only did those package names change but also the method names.

**Comment by confuser** [comment]
I see, seems like they're biting their own heads off. Appears Spigot hasn't pushed that change in their 1.4.5 build (Using a build that allows 1.4.6 clients to connect) hence the error. Seems stupid as it means every update, lots of plugins will have to update which just changes imports.

Thanks for the very fast response.
