### ISSUE TITLE
Moving away from an entity results in a dead entity

### ISSUE THREAD

**Issue by Lolmewn** [kumpelblase2/Remote-Entities#12]
It just dies. Huh.
The chunk seems to still be loaded, as I can see it in the client. They just despawn...

**Comment by kumpelblase2** [comment]
Does this still happen with 1.3 and/or the latest 1.4 snapshots?

**Comment by AmoebaMan** [comment]
It may be normal Minecraft behavior.  Try getting the Bukkit entity and calling setRemoveWhenFarAway(false)

**Comment by kolinkrewinkel** [comment]
Probably advisable to close this, @kumpelblase2. Encountered the same issue until using setRemoveWhenFarAway — otherwise, normal despawning interfered with my testing with early persistence branches.

**Comment by kumpelblase2** [comment]
@kolinkrewinkel ok.
