### ISSUE TITLE
RemoteEntityInteractEvent: Left or right click?

### ISSUE THREAD

**Issue by Lolmewn** [kumpelblase2/Remote-Entities#13]
Is there any way for me to check this already?
If not, could you maybe add it? 
Thanks, you're awesome!

**Comment by kumpelblase2** [comment]
Wouldn't left click mean damaging the entity?

**Comment by Lolmewn** [comment]
Ohyeah, I guess that could be something. I'd just have to do that... and that.. should work :)
Will try it out, closing this ticket for now.
