### ISSUE TITLE
Possible location saving problem

### ISSUE THREAD

**Issue by confuser** [kumpelblase2/Remote-Entities#15]
27.12 17:22:13 [Server] WARNING Wrong location for EntityZombie['Zombie'/228346, l='world', x=-161.00, y=77.00, z=-27.00] in world 'world'!

Getting a lot of these on start up and randomly spamming the console. This is the only server I have which does anything to mobs. We're getting a very low TPS as well. Restoring to an early backup seems to solve it but only temporarily as it starts again a few days later.

**Comment by IDragonfire** [comment]
What plugins did you use?

**Comment by confuser** [comment]
WorldBorder, WorldEdit, NoCheatPlus, EpicBoss, DonateIfFull, Friends, TagAPI, Buycraft, Vault, PermissionsEx, ColoredGroups, PlayersOnline, CapsGuard, WorldGuard, ColoredTablist, SignColours, ForumVerify, VaultTag, MineBackup, Spectate, ChestRestock, PointShop, BanManager, PlayerPoints, PlayerStatusSigns, Votifier, Blothera Assassin, RemoteEntities, AutoAnnouncer, LagMeter, Zombies

Where Zombies is my custom plugin using this library. PlayersOnline, ForumVerify, ColuredTablist, DonateIfFull & VaultTag are also custom plugins I've made. Everything else is from BukkitDev.

**Comment by confuser** [comment]
Ok I believe I found the issue. Basically too many RemoteEntities were being spawned (talking about 10k plus). This caused the main thread to lock and crash (Read time out), so I believe this is what was causing the issue. Still get the odd one or two of these every so often though but it's not really a massive issue.

The only way around it is to set a hard lock to the maximum number of entities that can be spawned however that should be done via a plugin and not the library, hence closing.
