### ISSUE TITLE
Add PlayerMoveEvent for RemotePlayer

### ISSUE THREAD

**Issue by kumpelblase2** [kumpelblase2/Remote-Entities#17]

**Comment by confuser** [comment]
Could this not cause issues with other plugins as technically they aren't an actual player?

**Comment by kumpelblase2** [comment]
Not more as the RemoteEntityPlayer itself. At least it shouldn't.

**Comment by kumpelblase2** [comment]
Created new issues to account for other new events as well. See #36 .
