### ISSUE TITLE
Fix DesireAttacks

### ISSUE THREAD

**Issue by IDragonfire** [kumpelblase2/Remote-Entities#19]
DesireAttackNearest no DesireAttackTarget don't work, no movment.
With DesireOnCollide NPC swing arms on collide, but player take no damage.
http://forums.bukkit.org/threads/lib-1-3-remote-entities-next-generation-npc-library.110304/page-4#post-1473752

Debugging says, that canExecuted is called, but startExecuted not ...
http://forums.bukkit.org/threads/lib-1-3-remote-entities-next-generation-npc-library.110304/page-4#post-1474215

**Comment by IDragonfire** [comment]
Hab ein wenig gedebugt mit "DesireAttackTarget" ...
shouldExecute ist immer false, außer der NPC wird angegriffen,
dann wird der Angreifer für ein paar Minuten als m_target gesetzt ...

**Comment by IDragonfire** [comment]
noch immer keine Reaktion ...
müsste nicht in der update Methode irgendwo ein attack Befehle stehen?

**Comment by IDragonfire** [comment]
Test Listener:

https://github.com/IDragonfire/Remote-Entities/blob/test/src/main/java/test/DAttackDesireTest.java

**Comment by kumpelblase2** [comment]
This "should" be fixed within the recent snapshots.
