### ISSUE TITLE
DesireLookAtNearest body movment

### ISSUE THREAD

**Issue by IDragonfire** [kumpelblase2/Remote-Entities#23]
Head has a unrealsitic position:

![2013-01-19_13 40 55](https://f.cloud.github.com/assets/1217999/80251/897f77d6-6235-11e2-94e6-f42f0c18157d.png)

**Comment by kolinkrewinkel** [comment]
I checked this out... Think we need to modify the lookAt() method in RemoteBaseEntity to include a teleport(), including a modified location with properly adjusted yaw.
