### ISSUE TITLE
DesireFollowSpecific requires EntityLiving

### ISSUE THREAD

**Issue by confuser** [kumpelblase2/Remote-Entities#24]
DesireFollowSpecific requires EntityLiving. Trying to get one mob follow another. Is this method supposed to be following specific types of mobs ie villagers rather than a specific entity? 

If that's the case, how would I get one entity to follow another entity around? Eg I want a zombie to follow a zombie leader/alpha.

**Comment by kumpelblase2** [comment]
No, if it should follow a specific type, you probably would need to pass over a class and not an instance of an entity.
It is doing what you said first, it will follow the given entity.
Hence, you can apply the same desire to all of the zombies and just set the target to the leader.

**Comment by confuser** [comment]
So how do I cast an Entity to an EntityLiving as I get errors saying it
can't be?

**Comment by kumpelblase2** [comment]
is it a bukkit entity? then ((CraftLivingEntity)bukkitEntity).getHandle()

**Comment by confuser** [comment]
Have I used it incorrectly?
http://pastebin.com/Mz40qYP7

`````` java
                    // Alpha check
                    EntityLiving alphaFound = null;
                    for (Entity e : z.getNearbyEntities(10, 10, 10)) {
                        if (craft.zombieAlphas.contains(e.getUniqueId())) {
                            alphaFound = ((CraftLivingEntity) e).getHandle();
                            break;
                        }
                    }

                    if (alphaFound != null) {
                        zomb.getMind().addActionDesire(new DesireFollowSpecific(zomb, alphaFound, 10L, 40L), 4);
                    }```
``````

**Comment by IDragonfire** [comment]
for the old version it was k,
but kumpelblase2 has change it (2h ago):
https://github.com/kumpelblase2/Remote-Entities/commit/7d86ed61eca2d9dede005b0e444dd028be220039

**Comment by kumpelblase2** [comment]
@confuser I was saying that if it's bukkit entity you should do that. But as far as I can see, it's a remote entity and thus not a bukkit entity but already a nms one. you should always do instance checks when casting. In this case, you should be able to safely cast to EntityLiving and later pass it over to the desire.

**Comment by confuser** [comment]
Oh I see. I just updated via Maven and it doesn't seem to have any changes? Latest .jar is pointing to 2012-12-27 on http://repo.infinityblade.de/remoteentities/index.php or am I just doing something completely wrong again? :(

**Comment by kumpelblase2** [comment]
There isn't a snapshot on the repository yet.

**Comment by confuser** [comment]
Ok, tried the latest snapshot. I'm still getting RemoteEntity cannot be casted as LivingEntity errors, no matter what I try. How do I use this desire to follow a RemoteEntity?

**Comment by IDragonfire** [comment]
Is that https://github.com/kumpelblase2/Remote-Entities/issues/24#issuecomment-12460769 still the current code?
You try to cast into the bukkit entity ...
Try:
`alphaFound = ((CraftLivingEntity) e).getBukkitEntity();`

**Comment by confuser** [comment]
Yes, but I've updated to the latest snapshot and 1.4.7. It seems that
RemoteEntity cannot be casted to LivingEntity, no matter what I try.

CraftLivingEntity has no such method getBukkitEntity, I believe that is only for a RemoteEntity object.

**Comment by IDragonfire** [comment]
Because a RemoteEntity IS NOT a LivingEntity: https://github.com/kumpelblase2/Remote-Entities/blob/master/src/main/java/de/kumpelblase2/remoteentities/api/RemoteEntity.java#L11

You must use

yourRemoteEntity.getBukkitEntity() for a BukkitEntity : LivingEntity (https://github.com/kumpelblase2/Remote-Entities/blob/master/src/main/java/de/kumpelblase2/remoteentities/api/RemoteEntity.java#L39)

or

yourRemoteEntity.getHandle() for a NmsEntity : EntityLiving  (https://github.com/kumpelblase2/Remote-Entities/blob/master/src/main/java/de/kumpelblase2/remoteentities/api/RemoteEntity.java#L46)

What is z in your example?

CraftLivingEntity is a LivingEntity,
not a EntityLiving!

But CraftLivingEntity has also a getHandle() method:
https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java#L225

The problem is,
that "e" is a Entity from Bukkit,
maybe a CraftLivingEntity.

**Comment by confuser** [comment]
Oh I see, thank you. Regarding getRemoteEntityByID within EntityManager, is that the ID relating to RemoteEntities or the ID of the actual Entity? Eg entity.getEntityID()? If not, as I can't get the LivingEntity to use the getRemoteEntityFromEntity, would I have to loop through all the entities within EntityManager to find the one I need?

**Comment by IDragonfire** [comment]
getRemoteEntityByID is only for RemoteEntites. 
I am not sure it the org.bukkit.Entity ID is equal to the RemoteEntity ID ...
kumpelblase2?

**Comment by IDragonfire** [comment]
Have you try this?

``` java
if(e instanceof CraftLivingEntity) {
    alphaFound = ((CraftLivingEntity) e).getHandle();
} else if(e instanceof RemoteZombieEntity ) {
    alphaFound = ((RemoteZombieEntity) e).getHandle()
} else {
    //throw an error
}
```

**Comment by confuser** [comment]
Just had a look through the code, it's not by the looks of it, the ID is based on getNextFreeID.

I'm still getting the class casting errors, looks like it's to do with the actual desire itself it seems.My zombieAlphas array ONLY contains entities which are RemoteEntities, there's no chance it could not be one.

Caused by: java.lang.ClassCastException: de.kumpelblase2.remoteentities.entities.RemoteZombieEntity cannot be cast to org.bukkit.entity.LivingEntity
2013-01-20 13:44:33 [SEVERE]    at de.kumpelblase2.remoteentities.api.thinking.goals.DesireFollowSpecific.update(DesireFollowSpecific.java:81)

``` java
                    // Alpha check
                    LivingEntity alphaFound = null;
                    for (Entity e : z.getNearbyEntities(10, 10, 10)) {
                        if (craft.zombieAlphas.contains(e.getUniqueId())) {
                            for (RemoteEntity r : craft.EntityManager.getAllEntities()) {
                                if (r.getBukkitEntity().getUniqueId().equals(e.getUniqueId())) {
                                    alphaFound = r.getBukkitEntity();
                                    break;
                                }
                            }
                            break;
                        }
                    }

                    if (alphaFound != null)
                        zomb.getMind().addActionDesire(new DesireFollowSpecific(zomb, alphaFound, 10L, 40L), 4);
```

**Comment by IDragonfire** [comment]
Take a look at my post above, like kumpelblase said, always do instance checks ...

``` java
// Alpha check
                    EntityLiving alphaFound = null;
                    for (Entity e : z.getNearbyEntities(10, 10, 10)) {
                        if (craft.zombieAlphas.contains(e.getUniqueId())) {
                           if(e instanceof CraftLivingEntity) {
                               alphaFound = ((CraftLivingEntity) e).getHandle();
                          } else if(e instanceof RemoteZombieEntity ) {
                                 alphaFound = ((RemoteZombieEntity) e).getHandle()
                           } else {
                                 //throw an error or maybe try tomething dirty with reflection?
                             }
                            break;
                        }
                    }
```

**Comment by confuser** [comment]
Exact same error, the else statement is never run, the e instanceof CraftLivingEntity is always true, e doesn't appear to be an instance of RemoteZombieEntity which is a little odd as if it's in the array list, then it will always be a RemoteEntity zombie

**Comment by kumpelblase2** [comment]
"I am not sure it the org.bukkit.Entity ID is equal to the RemoteEntity ID ...". Nope, the remote entity has its own id separate from the bukkit entity id.
For every kind of entity that you have, there's a way to get the remote entity or the other way around.
NMS entity:
for getting use: remoteentity.getHandle(). When having one, you 'should' be able to cast it: ((RemoteEntityHandle)entity).getRemoteEntity() .
Bukkit entity:
for getting use remoteentity.getBukkitEntity(). When having one, you can either do this: ((RemoteEntityHandle)((CraftLivingEntity)entity).getHandle()).getRemoteEntity() _or_ manager.getRemoteEntityFromEntity(entity)

These are the only available and necessary ways.

**Comment by IDragonfire** [comment]
https://github.com/kumpelblase2/Remote-Entities/commit/53f3ad4127d83644d1dae0cd0c2806cf38e3a87b

**Comment by confuser** [comment]
Thank you @kumpelblase2 and @IDragonfire. So when you get time to update the maven repo, alphaFound = ((CraftLivingEntity) e).getHandle(); with the follow desire should then work?
