### ISSUE TITLE
MC1.4.7 - Yep, a lot of people suddenly deciding to update.

### ISSUE THREAD

**Issue by Lolmewn** [kumpelblase2/Remote-Entities#26]
Since there's a Beta build for 1.4.7, a lot of my plugins' users are upgrading. RemoteEntities is still on 1.4.6, causing errors. So yeah, people make tickets and such, while there's nothing much I can do.

Is a 1.4.7 build available somewhere, or is it coming soon?

**Comment by IDragonfire** [comment]
The source is still ready for 1.4.7-R0.1...
Still some little things to fix ...
If you can't wait compile it^^

**Comment by IDragonfire** [comment]
http://forums.bukkit.org/threads/lib-1-3-remote-entities-next-generation-npc-library.110304/page-6#post-1512167

**Comment by Lolmewn** [comment]
Awesome, thanks. Will try this.
