### ISSUE TITLE
ChunkEntityLoader Concurrency modification exception

### ISSUE THREAD

**Issue by kolinkrewinkel** [kumpelblase2/Remote-Entities#32]
I've tried rewriting this completely, and encountered other bugs. Pretty pissed I couldn't get it working. Care to take a look?

Stack trace: http://k.krwnk.me/MoIr

When I moved it to the main thread using a runnable, it just didn't work at all for me.

**Comment by IDragonfire** [comment]
Have you tried a Hastable (threadsafe) instead a HasMap ... Looks like a Thread problem.

**Comment by kolinkrewinkel** [comment]
It's Bukkit's code in which the issue happens, though. (Still tried it though.) It all stems down from asking the Location for its chunk.

**Comment by kolinkrewinkel** [comment]
Fixed using this: https://github.com/kolinkrewinkel/Remote-Entities/commit/bf5543e4605c311e9417ab1edcbce66f6c1eace7

**Comment by kolinkrewinkel** [comment]
If you guys could take a look into this, it'd be great. I gave another try in my latest commit, and it's still awful. Try either. Please. :( The final nail of frustration was me asking Bukkit if a chunk was loaded and it always returning yes.

Edit: To note, the issue isn't just that exception. Pretty sure how we spawn things based on player's loading stuff in needs a thorough going-over.

**Comment by confuser** [comment]
Just got this in the latest build @kumpelblase2 did about 10 mins ago for me in irc but slightly different errors.

http://pastebin.com/FSsMK2Fw

I believe it's to do with the fact that chunk loading sometimes can be asynchronous, and therefore it's not always safe getting the bukkit entity?

Would a possible fix be running most of the chunk loading where possible within a runTask from the bukkit scheduler? That way it would be forced to run on the main thread. That's how I fixed spawning on ChunkLoadEvent within my plugin at least when converting certain mobs to RemoteEntities.

Edit: Strike that, just looked at the commit @kolinkrewinkel made, pretty much did what I just said.

**Comment by kolinkrewinkel** [comment]
I broke down in my fork and did an every tick repeating task that asks if the chunk is IN USE. Otherwise isLoaded returned untrue things and would appear to load the chunk upon being called. Fixed everything for me.

**Comment by kumpelblase2** [comment]
I forgot to reference it in the commit, but I hopefully fixed it in this commit: https://github.com/kumpelblase2/Remote-Entities/commit/c6dd31fafbb8997679c2c27e9bb92e342f8f1522
