### ISSUE TITLE
Removing entity from manager leaves entity without any logic.

### ISSUE THREAD

**Issue by ghost** [kumpelblase2/Remote-Entities#35]
Is it possible to reset the entities to their default logic, without re-spawning the entity?

**Comment by kumpelblase2** [comment]
What do you mean with "default logic"? Their default desires?

**Comment by ghost** [comment]
Yes.

**Comment by kumpelblase2** [comment]
Ok. Generally yes, but if you use your own nms entities with the library then no (if you don't add it yourself).
So what you want to do is clear both movement and action desires manually. Then you need to access the nms handle and call the setupStandardGoals method:
<code>
((RemoteEntityHandle)entity.getHandle()).setupStandardGoals();
</code>

**Comment by ghost** [comment]
Thank you! Works perfectly.
