### ISSUE TITLE
NPE on Create

### ISSUE THREAD

**Issue by confuser** [kumpelblase2/Remote-Entities#45]
Just updated to the latest 1.7-SNAPSHOT.

RemoteEntity zomb = craft.EntityManager.createRemoteEntityFromExisting(entity);

is causing the following errors where entity is CreatureSpawnEvent .getEntity()

http://pastebin.com/siTGjfMW

Any ideas?

Update:

To work around it, I cancelled all CreatureSpawnEvents and simply used the createEntity method. Not the nicest workaround, but it works.

**Comment by IDragonfire** [comment]
can you post your code?
does these jar fix the problem?
https://www.dropbox.com/sh/h0io2z7kaz762lm/3W9yv7gNAj

**Comment by confuser** [comment]
Code was as stated in original post. If I remember correctly, it was something along these lines. I was using my own spawnZombie method which contained the createRemoteFromEntity. The CreateSpawnEvent listener just had the checks to ensure it was a zombie before calling spawnZombie(). I re-factored months ago as stated in my "Update" to avoid the error.

onSpawn(CreatureSpawnEvent event) {

```
RemoteEntity zomb = craft.EntityManager.createRemoteEntityFromExisting(event.getEntity());
```

}

If this is fixed, that would be great and I could go back to the way I was originally creating them. Cancelling the creaturespawnevent is a big no no atm due to reasons stated on the Bukkit forums hence why it's not an ideal work around.

**Comment by kumpelblase2** [comment]
I have an attempt to fix it locally which should solve the issue, but I'll need to test.

**Comment by kumpelblase2** [comment]
I haven't referenced it in the commit, but I guess this one should fix it.
https://github.com/kumpelblase2/Remote-Entities/commit/cb0d2354efdf7df0c14cbf01b7cf0952e491014a
