### ISSUE TITLE
NPE on NPC save (setPathFindingRange or getPathFindingRange)

### ISSUE THREAD

**Issue by Silthus** [kumpelblase2/Remote-Entities#50]
When I want to save a created NPC it throws an NPE in the get and set PathFindingRage method.

Error: http://pastebin.com/5YNpDF5A
My creation code: http://pastebin.com/9u27pHxk

**Comment by IDragonfire** [comment]
Error is in:
https://github.com/kumpelblase2/Remote-Entities/blob/afebbe229e4f58007ba4b7d7b780ff413e34ea77/src/main/java/de/kumpelblase2/remoteentities/entities/RemoteBaseEntity.java#L405
GenericAttributes.b is null for human players

**Comment by IDragonfire** [comment]
better fix:
https://github.com/IDragonfire/Remote-Entities/commit/d54085f7e65abdcb5ea9d442a0bf5505c38153ee

**Comment by kumpelblase2** [comment]
Should be closed with this commit.
https://github.com/kumpelblase2/Remote-Entities/commit/ce63f4eeeb0336d6abaa65cacfb5efc3195b3da0
