### ISSUE TITLE
Reached end of stream for null

### ISSUE THREAD

**Issue by IDragonfire** [kumpelblase2/Remote-Entities#57]
Genera NPC plugin problem ...
console prints:
Reached end of stream for null

also on bukkit:
https://github.com/MinecraftPortCentral/MCPC-Plus/issues/67

**Comment by kumpelblase2** [comment]
The same fix I did for the old NPCLib from topcat long time ago should probably work with some change. I think I saw the same tactic on citizens too, so I guess that would fix it.

**Comment by IDragonfire** [comment]
that?
https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/util/NMS.java#L360

**Comment by kumpelblase2** [comment]
No. I solved it by increasing the buffer for the NullSocket.
https://github.com/kumpelblase2/Remote-Entities/blob/master/src/main/java/de/kumpelblase2/remoteentities/nms/NullSocket.java#L8

**Comment by IDragonfire** [comment]
ah, thx
