### ISSUE TITLE
NPE on create

### ISSUE THREAD

**Issue by ScottWoodward** [kumpelblase2/Remote-Entities#59]
I'm trying to create a Remote Entity, and I get a NPE every time I try.

The code I am executing
EntityManager manager = RemoteEntities.createManager(RPPets.plugin);
RemoteEntity pet =  manager.createEntity(RemoteEntityType.Zombie, ((Player)sender).getLocation());
pet.getMind().addMovementDesire(new DesireFollowSpecific((LivingEntity)sender, 5, 25), 1);

It spawns the creature, and it kind of follows the target, in that if the player gets more than 25 blocks away it teleports to them. 

Stack trace is here: http://pastebin.com/Cp5NGKjK

**Comment by IDragonfire** [comment]
@kumpelblase2:
I think this one:
https://github.com/kumpelblase2/Remote-Entities/blob/da028982fad9de8eb6f7275113b6e3b38acf40e5/src/main/java/de/kumpelblase2/remoteentities/api/thinking/goals/DesireSwim.java#L25

Zombie has no navigation ...

**Comment by kumpelblase2** [comment]
zombies HAVE navigation, in fact every entity except players has a navigation.
I did something wrong in the first release of 1.7 so I had to re-release it but I didn't change the version number. And I'm pretty sure what you're describing is exactly that what went wrong so redownloading it should probably solve the issue.

**Comment by ScottWoodward** [comment]
Downloaded a fresh copy from the Link on the Bukkit forums, same exact issue. Tried the two links to builds posted on github, one returns and HTTP 403 (Access Denied), the other just doesn't load. Where am I supposed to download it from?

Edit: Found it on dev.bukkit.

**Comment by kumpelblase2** [comment]
Damit, when I re-setup the server after it went down I uploaded the wrong wrong. You can find it on dev.bukkit.org and it should work with that one.
