### ISSUE TITLE
Desires

### ISSUE THREAD

**Issue by Merfin96** [kumpelblase2/Remote-Entities#60]
Needs alot of work on the DesireFollowTamer and DesireHelpAttacking desires. Only some entites will actually follow the tamer (e.g spider), and the only entity that i've seen to actually help attack is the skeleton.

**Comment by kumpelblase2** [comment]
Same here, I'm sorry that I've never responded, but I didn't even see this, I'm really sorry.
Just the follow or help desire is not enough, they need to have a desire which handles attacking, like MoveAndMeleeAttack.
