### ISSUE TITLE
Entities dont move

### ISSUE THREAD

**Issue by ptoews** [kumpelblase2/Remote-Entities#65]
I've spawned some entities and tried to make them move to a location by .move(), but they just stand there doing nothing. Here's the code:

```
    public Minion(Location spawnpoint, EntityManager manager, Team team) {
    this.team = team;
    entity = manager.createEntity(RemoteEntityType.Cow, spawnpoint, false);
    entity.setStationary(false);
}

public void setTarget(Location target) {
    entity.setSpeed(1);
    entity.move(target);
}
```

**Comment by Dread9Nought** [comment]
I am having this issue too, did you find a work around?

**Comment by ptoews** [comment]
Nope, not yet.

**Comment by Dread9Nought** [comment]
Damn it, I actually only recently came back to use this because I was having an issue a month or so ago, said issue is fixed... now I can't make entities move. :S - Maybe a previous snapshot will work?

Oh and just to clarify - .move() is returning true.

**Comment by ptoews** [comment]
Actually it worked in an other plugin, I needed to try it again and again but then it suddenly worked... Can't find the difference though.

**Comment by Dread9Nought** [comment]
Hmmmmm? Got any example code? I can't get it working for the life of me, but yea - I've had it working in a past plugin too(which I unfortunately don't have anymore)

**Comment by ptoews** [comment]
if(args[0].compareToIgnoreCase("spawn") == 0) {
                    entity = manager.createEntity(RemoteEntityType.Cow, player.getTargetBlock(null, 1000).getLocation().add(0, 1, 0), false);
                    entity.setStationary(false);
                    return true;
                } else if(args[0].compareToIgnoreCase("move") == 0) {
                    if(entity != null) {
                        entity.setSpeed(0.8);
                        entity.move(player);
                    }
                    return true;
                }

**Comment by Dread9Nought** [comment]
Hmmm, strange - It pretty much worked using your code - But when I modify what you have to:

 entity = manager.createNamedEntity(RemoteEntityType.Human, getBotSpawn(player.getLocation()), "Bot", false);
(getBotSpawn is just the loc given with x+2)

It just .. doesn't do a thing.

:/

**Comment by ptoews** [comment]
So the mistake is in the spawnpoint?

**Comment by Dread9Nought** [comment]
Oh no I meant I can see the fella - But he wont look at me nor move, but will do everything else I ask of him.

**Comment by Dread9Nought** [comment]
However - Setting desires and stuff appears to do its job, just not what I want.(excluding the Tame feature & Desire, that wont work for me either)

**Comment by joemort** [comment]
I have been having problems getting zombies, creepers, and golems to move since 1.6.4 update. I had them all functional beforehand when I was running remote-entities 1.6

**Comment by CrypticStorm** [comment]
Skeletons seem to work for aggro on hit, but also seem to not move toward a target. Default desires included. Something is definitely wrong.

**Comment by kumpelblase2** [comment]
This should have been fixed a while ago, so I'm closing this. Otherwise feel free to reopen it.
