### ISSUE TITLE
Is there no wither skeleton support?

### ISSUE THREAD

**Issue by Desty1** [kumpelblase2/Remote-Entities#66]
i've tried everything to get a remote skeleton with type of wither but it doesn't seem to have a setSkeletonType inside of RemoteSkeleton. Inless you are supposed to do it another way. If not please add this feature or some sort of support to turn a wither skeleton to a remote entity

**Comment by kumpelblase2** [comment]
There should be bukkit methods which provide this sort of functionality so it is not needed in here.
