### ISSUE TITLE
setHealth and onDeathEvent

### ISSUE THREAD

**Issue by 9903286** [kumpelblase2/Remote-Entities#68]
I would like to have a setHealth (getHealth?) and an DeathBehavior function.
If these functions already exist, please show me where, because i cannot find them.

**Comment by 9903286** [comment]
(setHealth and getHealth was accessible through getBukkitEntity(), sorry for that, but what about the DeathBehavior?)

**Comment by confuser** [comment]
Use the EntityDeathEvent and check if they are a remote entity.
