### ISSUE TITLE
Temporarily Despawn Entities

### ISSUE THREAD

**Issue by Lolmewn** [kumpelblase2/Remote-Entities#8]
I would very much like to have the ability of temporarily despawning entities.
With this, I mean the addition of two methods:
hideRemoteEntity() and showRemoteEntity(). Both would take a RemoteEntity as argument, and put it's ID in a HashSet perhaps? Then, when sending the NPC to the client, check if it's ID is in that set, and if so, continue.

I just don't know where all those things are, if I had I would've submitted a pull request :)

**Comment by kumpelblase2** [comment]
Is despawning them not an option? I mean, you can say that it shouldn't remove despawned entities (you can define that when creating the manager) and then despawn the entity temporarily. Hence, it will not get removed, won't make that much more work and will probably not cause any issues.

**Comment by kumpelblase2** [comment]
Closing this for now. When the way mentioned above is not acceptable for you, feel free to let me know.
