### ISSUE TITLE
Equiping kicks nearby players

### ISSUE THREAD

**Issue by confuser** [kumpelblase2/Remote-Entities#9]
``` java
// Spawns a zombie with the players equipment!
RemoteEntity zomb = craft.EntityManager.createEntity(RemoteEntityType.Zombie, event.getEntity().getLocation());

EquipmentFeature feature = new RemoteEquipmentFeature(zomb);        
// Get the player
Player p = player.getPlayer();

Equipment playerStuff = new Equipment(p.getItemInHand(), p.getInventory().getArmorContents());

feature.applyEquipment(playerStuff);

feature.updateEquipment();

// We now apply it to the entity
zomb.getFeatures().addFeature(feature);
```

The player is kicked for generic reason and the client shows End of Stream. Removing the equipment feature and the zombie appears to spawn fine with no issues on the client end.

**Comment by IDragonfire** [comment]
oO Any entries in the server log?

**Comment by confuser** [comment]
Nope, literally just says the player disconnected for generic reason in the console, and the player gets an End of Stream message on their client. If I remove the feature, everything works fine.

**Comment by kumpelblase2** [comment]
This feature will be removed as it's now natively accessible in craftbukkit.
see: https://github.com/Bukkit/CraftBukkit/commit/da4e272c58503c82d63e1461e8046429dca05b3e
and: https://github.com/Bukkit/Bukkit/commit/5d6592e5d2cb6d40398024ec24607e3f5bb0fac1
